import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        "neon-pink": {
          DEFAULT: "#f72585",
          50: "#fee6f1",
          100: "#fdd4e6",
          200: "#fca8ce",
          300: "#fa7db5",
          400: "#f9529d",
          500: "#f72585",
          600: "#dc0868",
          700: "#a5064e",
          800: "#6e0434",
          900: "#37021a",
          950: "#220110",
        },
        "raspberry-plum": {
          DEFAULT: "#b5179e",
          50: "#fce8f9",
          100: "#f8c9f1",
          200: "#f193e3",
          300: "#ea5dd5",
          400: "#e326c7",
          500: "#b5179e",
          600: "#90137e",
          700: "#6c0e5e",
          800: "#48093f",
          900: "#24051f",
          950: "#18031a",
        },
        "indigo-bloom": {
          DEFAULT: "#7209b7",
          50: "#f5e7fe",
          100: "#e5c3fc",
          200: "#cb86f9",
          300: "#b14af6",
          400: "#980df4",
          500: "#7209b7",
          600: "#5c0794",
          700: "#45056f",
          800: "#2e034a",
          900: "#170225",
          950: "#0e0118",
        },
        "ultrasonic-blue": {
          DEFAULT: "#560bad",
          50: "#f2e7fd",
          100: "#dcc2fb",
          200: "#ba84f7",
          300: "#9747f3",
          400: "#750fea",
          500: "#560bad",
          600: "#45098a",
          700: "#340768",
          800: "#230445",
          900: "#110223",
          950: "#0a0115",
        },
        "true-azure": {
          DEFAULT: "#480ca8",
          50: "#f0e7fd",
          100: "#d7c1fb",
          200: "#af83f6",
          300: "#8745f2",
          400: "#6210e5",
          500: "#480ca8",
          600: "#390986",
          700: "#2b0764",
          800: "#1c0543",
          900: "#0e0221",
          950: "#080114",
        },
        "vivid-royal": {
          DEFAULT: "#3a0ca3",
          50: "#eee7fd",
          100: "#d2c0fa",
          200: "#a582f6",
          300: "#7743f1",
          400: "#4f11e0",
          500: "#3a0ca3",
          600: "#2e0a81",
          700: "#220761",
          800: "#170541",
          900: "#0b0220",
          950: "#070114",
        },
        "bright-indigo": {
          DEFAULT: "#3f37c9",
          50: "#ecebfa",
          100: "#d8d7f4",
          200: "#b2afe9",
          300: "#8b87de",
          400: "#655fd3",
          500: "#3f37c9",
          600: "#322ca0",
          700: "#252178",
          800: "#191650",
          900: "#0c0b28",
          950: "#08071a",
        },
        "electric-sapphire": {
          DEFAULT: "#4361ee",
          50: "#e8ecfd",
          100: "#dae0fc",
          200: "#b4c1f8",
          300: "#8fa2f5",
          400: "#6a83f1",
          500: "#4361ee",
          600: "#153ae0",
          700: "#102ca8",
          800: "#0a1d70",
          900: "#050f38",
          950: "#030924",
        },
        "blue-energy": {
          DEFAULT: "#4895ef",
          50: "#e8f2fd",
          100: "#daeafc",
          200: "#b6d5f9",
          300: "#91c0f5",
          400: "#6dabf2",
          500: "#4895ef",
          600: "#1475e5",
          700: "#0f58ac",
          800: "#0a3b72",
          900: "#051d39",
          950: "#031124",
        },
        "sky-aqua": {
          DEFAULT: "#4cc9f0",
          50: "#e7f8fd",
          100: "#dbf4fc",
          200: "#b7eaf9",
          300: "#93dff6",
          400: "#70d5f3",
          500: "#4cc9f0",
          600: "#13b8ea",
          700: "#0e8aaf",
          800: "#095c75",
          900: "#052e3a",
          950: "#031c24",
        },
        // Resume template colors
        "light-coral": {
          DEFAULT: "hsl(var(--light-coral))",
          light: "hsl(var(--light-coral-light))",
        },
        "deep-pink": {
          DEFAULT: "hsl(var(--deep-pink))",
          light: "hsl(var(--deep-pink-light))",
        },
        "dark-orange": {
          DEFAULT: "hsl(var(--dark-orange))",
          light: "hsl(var(--dark-orange-light))",
        },
        "medium-orchid": {
          DEFAULT: "hsl(var(--medium-orchid))",
          light: "hsl(var(--medium-orchid-light))",
        },
        teal: {
          DEFAULT: "hsl(var(--teal))",
          light: "hsl(var(--teal-light))",
        },
        "dark-turquoise": {
          DEFAULT: "hsl(var(--dark-turquoise))",
          light: "hsl(var(--dark-turquoise-light))",
        },
        "olive-drab": {
          DEFAULT: "hsl(var(--olive-drab))",
          light: "hsl(var(--olive-drab-light))",
        },
        "medium-blue": {
          DEFAULT: "hsl(var(--medium-blue))",
          light: "hsl(var(--medium-blue-light))",
        },
        coral: {
          DEFAULT: "hsl(var(--coral))",
          light: "hsl(var(--coral-light))",
        },
        "royal-blue": {
          DEFAULT: "hsl(var(--royal-blue))",
          light: "hsl(var(--royal-blue-light))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "calc(var(--radius) + 4px)",
        "2xl": "calc(var(--radius) + 8px)",
      },
      boxShadow: {
        soft: "var(--shadow-md)",
        glow: "var(--shadow-glow)",
        card: "0 4px 20px -2px hsl(var(--indigo-bloom-500) / 0.12)",
        "card-hover": "0 8px 30px -4px hsl(var(--indigo-bloom-500) / 0.18)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "slide-in-right": {
          "0%": { opacity: "0", transform: "translateX(20px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out forwards",
        "fade-in-up": "fade-in-up 0.6s ease-out forwards",
        "scale-in": "scale-in 0.3s ease-out forwards",
        "slide-in-right": "slide-in-right 0.4s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
