import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        "neon-pink": {
          50: "hsl(var(--neon-pink-50))",
          100: "hsl(var(--neon-pink-100))",
          200: "hsl(var(--neon-pink-200))",
          300: "hsl(var(--neon-pink-300))",
          400: "hsl(var(--neon-pink-400))",
          500: "hsl(var(--neon-pink-500))",
          600: "hsl(var(--neon-pink-600))",
          700: "hsl(var(--neon-pink-700))",
          800: "hsl(var(--neon-pink-800))",
          900: "hsl(var(--neon-pink-900))",
          950: "hsl(var(--neon-pink-950))",
        },
        "raspberry-plum": {
          50: "hsl(var(--raspberry-plum-50))",
          100: "hsl(var(--raspberry-plum-100))",
          200: "hsl(var(--raspberry-plum-200))",
          300: "hsl(var(--raspberry-plum-300))",
          400: "hsl(var(--raspberry-plum-400))",
          500: "hsl(var(--raspberry-plum-500))",
          600: "hsl(var(--raspberry-plum-600))",
          700: "hsl(var(--raspberry-plum-700))",
          800: "hsl(var(--raspberry-plum-800))",
          900: "hsl(var(--raspberry-plum-900))",
          950: "hsl(var(--raspberry-plum-950))",
        },
        "indigo-bloom": {
          50: "hsl(var(--indigo-bloom-50))",
          100: "hsl(var(--indigo-bloom-100))",
          200: "hsl(var(--indigo-bloom-200))",
          300: "hsl(var(--indigo-bloom-300))",
          400: "hsl(var(--indigo-bloom-400))",
          500: "hsl(var(--indigo-bloom-500))",
          600: "hsl(var(--indigo-bloom-600))",
          700: "hsl(var(--indigo-bloom-700))",
          800: "hsl(var(--indigo-bloom-800))",
          900: "hsl(var(--indigo-bloom-900))",
          950: "hsl(var(--indigo-bloom-950))",
        },
        "ultrasonic-blue": {
          50: "hsl(var(--ultrasonic-blue-50))",
          100: "hsl(var(--ultrasonic-blue-100))",
          200: "hsl(var(--ultrasonic-blue-200))",
          300: "hsl(var(--ultrasonic-blue-300))",
          400: "hsl(var(--ultrasonic-blue-400))",
          500: "hsl(var(--ultrasonic-blue-500))",
          600: "hsl(var(--ultrasonic-blue-600))",
          700: "hsl(var(--ultrasonic-blue-700))",
          800: "hsl(var(--ultrasonic-blue-800))",
          900: "hsl(var(--ultrasonic-blue-900))",
          950: "hsl(var(--ultrasonic-blue-950))",
        },
        "true-azure": {
          50: "hsl(var(--true-azure-50))",
          100: "hsl(var(--true-azure-100))",
          200: "hsl(var(--true-azure-200))",
          300: "hsl(var(--true-azure-300))",
          400: "hsl(var(--true-azure-400))",
          500: "hsl(var(--true-azure-500))",
          600: "hsl(var(--true-azure-600))",
          700: "hsl(var(--true-azure-700))",
          800: "hsl(var(--true-azure-800))",
          900: "hsl(var(--true-azure-900))",
          950: "hsl(var(--true-azure-950))",
        },
        "vivid-royal": {
          50: "hsl(var(--vivid-royal-50))",
          100: "hsl(var(--vivid-royal-100))",
          200: "hsl(var(--vivid-royal-200))",
          300: "hsl(var(--vivid-royal-300))",
          400: "hsl(var(--vivid-royal-400))",
          500: "hsl(var(--vivid-royal-500))",
          600: "hsl(var(--vivid-royal-600))",
          700: "hsl(var(--vivid-royal-700))",
          800: "hsl(var(--vivid-royal-800))",
          900: "hsl(var(--vivid-royal-900))",
          950: "hsl(var(--vivid-royal-950))",
        },
        "bright-indigo": {
          50: "hsl(var(--bright-indigo-50))",
          100: "hsl(var(--bright-indigo-100))",
          200: "hsl(var(--bright-indigo-200))",
          300: "hsl(var(--bright-indigo-300))",
          400: "hsl(var(--bright-indigo-400))",
          500: "hsl(var(--bright-indigo-500))",
          600: "hsl(var(--bright-indigo-600))",
          700: "hsl(var(--bright-indigo-700))",
          800: "hsl(var(--bright-indigo-800))",
          900: "hsl(var(--bright-indigo-900))",
          950: "hsl(var(--bright-indigo-950))",
        },
        "electric-sapphire": {
          50: "hsl(var(--electric-sapphire-50))",
          100: "hsl(var(--electric-sapphire-100))",
          200: "hsl(var(--electric-sapphire-200))",
          300: "hsl(var(--electric-sapphire-300))",
          400: "hsl(var(--electric-sapphire-400))",
          500: "hsl(var(--electric-sapphire-500))",
          600: "hsl(var(--electric-sapphire-600))",
          700: "hsl(var(--electric-sapphire-700))",
          800: "hsl(var(--electric-sapphire-800))",
          900: "hsl(var(--electric-sapphire-900))",
          950: "hsl(var(--electric-sapphire-950))",
        },
        "blue-energy": {
          50: "hsl(var(--blue-energy-50))",
          100: "hsl(var(--blue-energy-100))",
          200: "hsl(var(--blue-energy-200))",
          300: "hsl(var(--blue-energy-300))",
          400: "hsl(var(--blue-energy-400))",
          500: "hsl(var(--blue-energy-500))",
          600: "hsl(var(--blue-energy-600))",
          700: "hsl(var(--blue-energy-700))",
          800: "hsl(var(--blue-energy-800))",
          900: "hsl(var(--blue-energy-900))",
          950: "hsl(var(--blue-energy-950))",
        },
        "sky-aqua": {
          50: "hsl(var(--sky-aqua-50))",
          100: "hsl(var(--sky-aqua-100))",
          200: "hsl(var(--sky-aqua-200))",
          300: "hsl(var(--sky-aqua-300))",
          400: "hsl(var(--sky-aqua-400))",
          500: "hsl(var(--sky-aqua-500))",
          600: "hsl(var(--sky-aqua-600))",
          700: "hsl(var(--sky-aqua-700))",
          800: "hsl(var(--sky-aqua-800))",
          900: "hsl(var(--sky-aqua-900))",
          950: "hsl(var(--sky-aqua-950))",
        },
        // Resume template colors
        "light-coral": {
          DEFAULT: "hsl(var(--light-coral))",
          light: "hsl(var(--light-coral-light))",
        },
        "deep-pink": {
          DEFAULT: "hsl(var(--deep-pink))",
          light: "hsl(var(--deep-pink-light))",
        },
        "dark-orange": {
          DEFAULT: "hsl(var(--dark-orange))",
          light: "hsl(var(--dark-orange-light))",
        },
        "medium-orchid": {
          DEFAULT: "hsl(var(--medium-orchid))",
          light: "hsl(var(--medium-orchid-light))",
        },
        teal: {
          DEFAULT: "hsl(var(--teal))",
          light: "hsl(var(--teal-light))",
        },
        "dark-turquoise": {
          DEFAULT: "hsl(var(--dark-turquoise))",
          light: "hsl(var(--dark-turquoise-light))",
        },
        "olive-drab": {
          DEFAULT: "hsl(var(--olive-drab))",
          light: "hsl(var(--olive-drab-light))",
        },
        "medium-blue": {
          DEFAULT: "hsl(var(--medium-blue))",
          light: "hsl(var(--medium-blue-light))",
        },
        coral: {
          DEFAULT: "hsl(var(--coral))",
          light: "hsl(var(--coral-light))",
        },
        "royal-blue": {
          DEFAULT: "hsl(var(--royal-blue))",
          light: "hsl(var(--royal-blue-light))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "calc(var(--radius) + 4px)",
        "2xl": "calc(var(--radius) + 8px)",
      },
      boxShadow: {
        soft: "var(--shadow-md)",
        glow: "var(--shadow-glow)",
        card: "0 4px 20px -2px hsl(var(--indigo-bloom-500) / 0.12)",
        "card-hover": "0 8px 30px -4px hsl(var(--indigo-bloom-500) / 0.18)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "slide-in-right": {
          "0%": { opacity: "0", transform: "translateX(20px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out forwards",
        "fade-in-up": "fade-in-up 0.6s ease-out forwards",
        "scale-in": "scale-in 0.3s ease-out forwards",
        "slide-in-right": "slide-in-right 0.4s ease-out forwards",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
