import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Inter', 'Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'Inter', 'system-ui', 'sans-serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        "royal-violet": {
          DEFAULT: "#7400b8",
          50: "#f5e7fe",
          100: "#37021a",
          200: "#6e0434",
          300: "#a5064e",
          400: "#5d0093",
          500: "#7400b8",
          600: "#9e00f9",
          700: "#b73bff",
          800: "#cf7cff",
          900: "#e7beff",
        },
        "indigo-bloom": {
          DEFAULT: "#6930c3",
          50: "#f0e7fd",
          100: "#150a27",
          200: "#2a144e",
          300: "#3f1d76",
          400: "#54279d",
          500: "#6930c3",
          600: "#8655d5",
          700: "#a480df",
          800: "#c3aaea",
          900: "#e1d5f4",
        },
        "slate-blue": {
          DEFAULT: "#5e60ce",
          50: "#ededfa",
          100: "#0c0b28",
          200: "#191650",
          300: "#252178",
          400: "#322ca0",
          500: "#5e60ce",
          600: "#7f81d8",
          700: "#9fa0e2",
          800: "#bfc0eb",
          900: "#dfdff5",
        },
        "cloudy-sky": {
          DEFAULT: "#5390d9",
          50: "#e9f0fb",
          100: "#0b1c31",
          200: "#163863",
          300: "#205494",
          400: "#2b71c5",
          500: "#5390d9",
          600: "#76a6e1",
          700: "#98bce8",
          800: "#bad3f0",
          900: "#dde9f7",
        },
        "fresh-sky": {
          DEFAULT: "#4ea8de",
          50: "#e8f4fb",
          100: "#092333",
          200: "#134666",
          300: "#1c6999",
          400: "#258ccb",
          500: "#4ea8de",
          600: "#72b9e5",
          700: "#95caec",
          800: "#b8dcf2",
          900: "#dcedf9",
        },
        "sky-surge": {
          DEFAULT: "#48bfe3",
          50: "#e7f6fb",
          100: "#082a34",
          200: "#105468",
          300: "#187d9c",
          400: "#20a7d0",
          500: "#48bfe3",
          600: "#6ecce8",
          700: "#92d9ee",
          800: "#b7e5f4",
          900: "#dbf2f9",
        },
        "sky-blue-light": {
          DEFAULT: "#56cfe1",
          50: "#e8f7fa",
          100: "#092f35",
          200: "#135e6a",
          300: "#1c8d9f",
          400: "#25bcd4",
          500: "#56cfe1",
          600: "#78d8e7",
          700: "#9ae2ed",
          800: "#bbecf3",
          900: "#ddf5f9",
        },
        "pearl-aqua": {
          DEFAULT: "#64dfdf",
          50: "#e6f9f9",
          100: "#0b3535",
          200: "#166b6b",
          300: "#21a0a0",
          400: "#2dd4d4",
          500: "#64dfdf",
          600: "#82e5e5",
          700: "#a1ecec",
          800: "#c0f2f2",
          900: "#e0f9f9",
        },
        "turquoise": {
          DEFAULT: "#72efdd",
          50: "#e5fcf8",
          100: "#073f37",
          200: "#0e7f6e",
          300: "#15bea5",
          400: "#31e8cd",
          500: "#72efdd",
          600: "#8df2e3",
          700: "#aaf6ea",
          800: "#c6f9f1",
          900: "#e3fcf8",
        },
        "aquamarine": {
          DEFAULT: "#80ffdb",
          50: "#e5fff8",
          100: "#004d37",
          200: "#00996e",
          300: "#00e6a4",
          400: "#33ffc5",
          500: "#80ffdb",
          600: "#99ffe2",
          700: "#b3ffe9",
          800: "#ccfff1",
          900: "#e5fff8",
        },
        // Resume template colors
        "light-coral": {
          DEFAULT: "hsl(var(--light-coral))",
          light: "hsl(var(--light-coral-light))",
        },
        "deep-pink": {
          DEFAULT: "hsl(var(--deep-pink))",
          light: "hsl(var(--deep-pink-light))",
        },
        "dark-orange": {
          DEFAULT: "hsl(var(--dark-orange))",
          light: "hsl(var(--dark-orange-light))",
        },
        "medium-orchid": {
          DEFAULT: "hsl(var(--medium-orchid))",
          light: "hsl(var(--medium-orchid-light))",
        },
        teal: {
          DEFAULT: "hsl(var(--teal))",
          light: "hsl(var(--teal-light))",
        },
        "dark-turquoise": {
          DEFAULT: "hsl(var(--dark-turquoise))",
          light: "hsl(var(--dark-turquoise-light))",
        },
        "olive-drab": {
          DEFAULT: "hsl(var(--olive-drab))",
          light: "hsl(var(--olive-drab-light))",
        },
        "medium-blue": {
          DEFAULT: "hsl(var(--medium-blue))",
          light: "hsl(var(--medium-blue-light))",
        },
        coral: {
          DEFAULT: "hsl(var(--coral))",
          light: "hsl(var(--coral-light))",
        },
        "royal-blue": {
          DEFAULT: "hsl(var(--royal-blue))",
          light: "hsl(var(--royal-blue-light))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "calc(var(--radius) + 4px)",
        "2xl": "calc(var(--radius) + 8px)",
      },
      boxShadow: {
        soft: "var(--shadow-md)",
        glow: "var(--shadow-glow)",
        card: "0 4px 20px -2px hsl(261 88% 20% / 0.3)",
        "card-hover": "0 8px 30px -4px hsl(157 100% 75% / 0.15)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "slide-in-right": {
          "0%": { opacity: "0", transform: "translateX(20px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "bubble-rise": {
          "0%": { transform: "translateY(0) scale(1)", opacity: "0.5" },
          "50%": { transform: "translateY(-40px) scale(1.15)", opacity: "0.3" },
          "100%": { transform: "translateY(0) scale(1)", opacity: "0.5" },
        },
        "bubble-drift": {
          "0%": { transform: "translate(0, 0) scale(1)", opacity: "0.5" },
          "33%": { transform: "translate(15px, -30px) scale(1.1)", opacity: "0.35" },
          "66%": { transform: "translate(-10px, -15px) scale(0.95)", opacity: "0.45" },
          "100%": { transform: "translate(0, 0) scale(1)", opacity: "0.5" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out forwards",
        "fade-in-up": "fade-in-up 0.6s ease-out forwards",
        "scale-in": "scale-in 0.3s ease-out forwards",
        "slide-in-right": "slide-in-right 0.4s ease-out forwards",
        "bubble-1": "bubble-rise 7s ease-in-out infinite",
        "bubble-2": "bubble-drift 9s ease-in-out infinite 1s",
        "bubble-3": "bubble-rise 11s ease-in-out infinite 2s",
        "bubble-4": "bubble-drift 8s ease-in-out infinite 0.5s",
        "bubble-5": "bubble-rise 10s ease-in-out infinite 3s",
        "bubble-6": "bubble-drift 12s ease-in-out infinite 1.5s",
        "bubble-7": "bubble-rise 9s ease-in-out infinite 4s",
        "bubble-8": "bubble-drift 10s ease-in-out infinite 2.5s",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
